Can't work out where the error is
Error: Problem with `filter()` input `..1`.
ℹ Input `..1` is `SchoolID == SchoolChosen$SchoolID`.
x Input `..1` must be of size 1, not size 0.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In max(NumberKidsPerSchool$NumberKids) :
  no non-missing arguments to max; returning -Inf