Put the return in the wrong place, but got the following error for household 593:
Error: Problem with `filter()` input `..1`.
x Input `..1` must be of size 2 or 1, not size 0.
ℹ Input `..1` is `ChildAge == AgeToUse$ChildAge`.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In max(CheckForMultiples$NumberKidsThatAge) :
  no non-missing arguments to max; returning -Inf