Subsetting mother counts works, trying to get a subset based on the filter of MinProp counts. However, break is throwing an error and need to fix that first.
Error: Error in FUN(X[[i]], ...) : no loop for break/next, jumping to top level